# Site Setup
title:                Jesse Adametz
tagline:              'Data Engineer in sunny Santa Barbara, CA.'
description:          'Passionate about automation, productivity, elegant design, and craft beer.'


# URL Setup
url:                  https://www.jesseadametz.com
baseurl:              ''
paginate:             2
permalink:            pretty
relative_permalinks:  true


# About
author:
  name:               Jesse Adametz
  url:                https://twitter.com/jesseadametz
  github:             https://github.com/jadametz


# Jekyll stuff
markdown:             redcarpet
highlighter:          pygments


# redcarpet stuff
redcarpet:
  extensions:         ['smart', 'strikethrough', 'tables']


# Custom vars
version:              1.0.0

# front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
